// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Category struct {
	ID   int32
	Name string
}

type Exercise struct {
	ID          int32
	Name        string
	Description string
}

type ExerciseCategory struct {
	ExerciseID int32
	CategoryID int32
}

type ExerciseMuscleGroup struct {
	ExerciseID    int32
	MuscleGroupID int32
}

type MuscleGroup struct {
	ID   int32
	Name string
}

type User struct {
	ID       int32
	Username string
	Email    string
	Password string
	Salt     string
}
